//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:4.0.30319.42000
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace Arkivverket.Arkade.ExternalModels.ChangeLog {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/endringslogg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/endringslogg", IsNullable=false)]
    public partial class endringslogg {
        
        private endring[] endringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("endring")]
        public endring[] endring {
            get {
                return this.endringField;
            }
            set {
                this.endringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/endringslogg")]
    public partial class endring {
        
        private string referanseArkivenhetField;
        
        private string referanseMetadataField;
        
        private System.DateTime endretDatoField;
        
        private string endretAvField;
        
        private string tidligereVerdiField;
        
        private string nyVerdiField;
        
        /// <remarks/>
        public string referanseArkivenhet {
            get {
                return this.referanseArkivenhetField;
            }
            set {
                this.referanseArkivenhetField = value;
            }
        }
        
        /// <remarks/>
        public string referanseMetadata {
            get {
                return this.referanseMetadataField;
            }
            set {
                this.referanseMetadataField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime endretDato {
            get {
                return this.endretDatoField;
            }
            set {
                this.endretDatoField = value;
            }
        }
        
        /// <remarks/>
        public string endretAv {
            get {
                return this.endretAvField;
            }
            set {
                this.endretAvField = value;
            }
        }
        
        /// <remarks/>
        public string tidligereVerdi {
            get {
                return this.tidligereVerdiField;
            }
            set {
                this.tidligereVerdiField = value;
            }
        }
        
        /// <remarks/>
        public string nyVerdi {
            get {
                return this.nyVerdiField;
            }
            set {
                this.nyVerdiField = value;
            }
        }
    }
}
