//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:4.0.30319.42000
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace Arkivverket.Arkade.ExternalModels.RunningJournal {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/loependeJournal")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/loependeJournal", IsNullable=false)]
    public partial class loependeJournal {
        
        private journalhode journalhodeField;
        
        private journalregistrering[] journalregistreringField;
        
        /// <remarks/>
        public journalhode journalhode {
            get {
                return this.journalhodeField;
            }
            set {
                this.journalhodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("journalregistrering")]
        public journalregistrering[] journalregistrering {
            get {
                return this.journalregistreringField;
            }
            set {
                this.journalregistreringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/loependeJournal")]
    public partial class journalhode {
        
        private System.DateTime journalStartDatoField;
        
        private System.DateTime journalSluttDatoField;
        
        private string seleksjonField;
        
        private string antallJournalposterField;
        
        private arkivskaper[] arkivskaperField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime journalStartDato {
            get {
                return this.journalStartDatoField;
            }
            set {
                this.journalStartDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime journalSluttDato {
            get {
                return this.journalSluttDatoField;
            }
            set {
                this.journalSluttDatoField = value;
            }
        }
        
        /// <remarks/>
        public string seleksjon {
            get {
                return this.seleksjonField;
            }
            set {
                this.seleksjonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string antallJournalposter {
            get {
                return this.antallJournalposterField;
            }
            set {
                this.antallJournalposterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("arkivskaper")]
        public arkivskaper[] arkivskaper {
            get {
                return this.arkivskaperField;
            }
            set {
                this.arkivskaperField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/loependeJournal")]
    public partial class arkivskaper {
        
        private string arkivskaperIDField;
        
        private string arkivskaperNavnField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string arkivskaperID {
            get {
                return this.arkivskaperIDField;
            }
            set {
                this.arkivskaperIDField = value;
            }
        }
        
        /// <remarks/>
        public string arkivskaperNavn {
            get {
                return this.arkivskaperNavnField;
            }
            set {
                this.arkivskaperNavnField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/loependeJournal")]
    public partial class korrespondansepart {
        
        private korrespondanseparttype korrespondanseparttypeField;
        
        private string korrespondansepartNavnField;
        
        private string skjermingMetadataField;
        
        /// <remarks/>
        public korrespondanseparttype korrespondanseparttype {
            get {
                return this.korrespondanseparttypeField;
            }
            set {
                this.korrespondanseparttypeField = value;
            }
        }
        
        /// <remarks/>
        public string korrespondansepartNavn {
            get {
                return this.korrespondansepartNavnField;
            }
            set {
                this.korrespondansepartNavnField = value;
            }
        }
        
        /// <remarks/>
        public string skjermingMetadata {
            get {
                return this.skjermingMetadataField;
            }
            set {
                this.skjermingMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/metadatakatalog")]
    public enum korrespondanseparttype {
        
        /// <remarks/>
        Avsender,
        
        /// <remarks/>
        Mottaker,
        
        /// <remarks/>
        Kopimottaker,
        
        /// <remarks/>
        Gruppemottaker,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Intern avsender")]
        Internavsender,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Intern mottaker")]
        Internmottaker,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/loependeJournal")]
    public partial class journalpost {
        
        private string systemIDField;
        
        private string journalaarField;
        
        private string journalsekvensnummerField;
        
        private string journalpostnummerField;
        
        private string tittelField;
        
        private string offentligTittelField;
        
        private string skjermingMetadataField;
        
        private System.DateTime journaldatoField;
        
        private System.DateTime dokumentetsDatoField;
        
        private bool dokumentetsDatoFieldSpecified;
        
        private System.DateTime avskrivningsdatoField;
        
        private bool avskrivningsdatoFieldSpecified;
        
        private avskrivningsmaate avskrivningsmaateField;
        
        private bool avskrivningsmaateFieldSpecified;
        
        private string referanseAvskrivesAvJournalpostField;
        
        private string tilgangsrestriksjonField;
        
        private gradering graderingField;
        
        private bool graderingFieldSpecified;
        
        private string skjermingshjemmelField;
        
        private korrespondansepart[] korrespondansepartField;
        
        /// <remarks/>
        public string systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string journalaar {
            get {
                return this.journalaarField;
            }
            set {
                this.journalaarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string journalsekvensnummer {
            get {
                return this.journalsekvensnummerField;
            }
            set {
                this.journalsekvensnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string journalpostnummer {
            get {
                return this.journalpostnummerField;
            }
            set {
                this.journalpostnummerField = value;
            }
        }
        
        /// <remarks/>
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        public string offentligTittel {
            get {
                return this.offentligTittelField;
            }
            set {
                this.offentligTittelField = value;
            }
        }
        
        /// <remarks/>
        public string skjermingMetadata {
            get {
                return this.skjermingMetadataField;
            }
            set {
                this.skjermingMetadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime journaldato {
            get {
                return this.journaldatoField;
            }
            set {
                this.journaldatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dokumentetsDato {
            get {
                return this.dokumentetsDatoField;
            }
            set {
                this.dokumentetsDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dokumentetsDatoSpecified {
            get {
                return this.dokumentetsDatoFieldSpecified;
            }
            set {
                this.dokumentetsDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime avskrivningsdato {
            get {
                return this.avskrivningsdatoField;
            }
            set {
                this.avskrivningsdatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avskrivningsdatoSpecified {
            get {
                return this.avskrivningsdatoFieldSpecified;
            }
            set {
                this.avskrivningsdatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public avskrivningsmaate avskrivningsmaate {
            get {
                return this.avskrivningsmaateField;
            }
            set {
                this.avskrivningsmaateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avskrivningsmaateSpecified {
            get {
                return this.avskrivningsmaateFieldSpecified;
            }
            set {
                this.avskrivningsmaateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string referanseAvskrivesAvJournalpost {
            get {
                return this.referanseAvskrivesAvJournalpostField;
            }
            set {
                this.referanseAvskrivesAvJournalpostField = value;
            }
        }
        
        /// <remarks/>
        public string tilgangsrestriksjon {
            get {
                return this.tilgangsrestriksjonField;
            }
            set {
                this.tilgangsrestriksjonField = value;
            }
        }
        
        /// <remarks/>
        public gradering gradering {
            get {
                return this.graderingField;
            }
            set {
                this.graderingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool graderingSpecified {
            get {
                return this.graderingFieldSpecified;
            }
            set {
                this.graderingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string skjermingshjemmel {
            get {
                return this.skjermingshjemmelField;
            }
            set {
                this.skjermingshjemmelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("korrespondansepart")]
        public korrespondansepart[] korrespondansepart {
            get {
                return this.korrespondansepartField;
            }
            set {
                this.korrespondansepartField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/metadatakatalog")]
    public enum avskrivningsmaate {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Besvart med brev")]
        Besvartmedbrev,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Besvart med e-post")]
        Besvartmedepost,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Besvart på telefon")]
        Besvartpåtelefon,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Tatt til etterretning")]
        Tatttiletterretning,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Tatt til orientering")]
        Tatttilorientering,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/metadatakatalog")]
    public enum gradering {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Strengt hemmelig (sikkerhetsgrad)")]
        Strengthemmeligsikkerhetsgrad,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Hemmelig (sikkerhetsgrad)")]
        Hemmeligsikkerhetsgrad,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Konfidensielt (sikkerhetsgrad)")]
        Konfidensieltsikkerhetsgrad,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Begrenset (sikkerhetsgrad)")]
        Begrensetsikkerhetsgrad,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Fortrolig (beskyttelsesgrad)")]
        Fortroligbeskyttelsesgrad,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Strengt fortrolig (beskyttelsesgrad)")]
        Strengtfortroligbeskyttelsesgrad,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/loependeJournal")]
    public partial class saksmappe {
        
        private string saksaarField;
        
        private string sakssekvensnummerField;
        
        private string tittelField;
        
        private string offentligTittelField;
        
        private string skjermingMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string saksaar {
            get {
                return this.saksaarField;
            }
            set {
                this.saksaarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string sakssekvensnummer {
            get {
                return this.sakssekvensnummerField;
            }
            set {
                this.sakssekvensnummerField = value;
            }
        }
        
        /// <remarks/>
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        public string offentligTittel {
            get {
                return this.offentligTittelField;
            }
            set {
                this.offentligTittelField = value;
            }
        }
        
        /// <remarks/>
        public string skjermingMetadata {
            get {
                return this.skjermingMetadataField;
            }
            set {
                this.skjermingMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/loependeJournal")]
    public partial class klasse {
        
        private string klasseIDField;
        
        private string tittelField;
        
        private string[] skjermingMetadataField;
        
        /// <remarks/>
        public string klasseID {
            get {
                return this.klasseIDField;
            }
            set {
                this.klasseIDField = value;
            }
        }
        
        /// <remarks/>
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("skjermingMetadata")]
        public string[] skjermingMetadata {
            get {
                return this.skjermingMetadataField;
            }
            set {
                this.skjermingMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/loependeJournal")]
    public partial class journalregistrering {
        
        private klasse klasseField;
        
        private saksmappe saksmappeField;
        
        private journalpost journalpostField;
        
        /// <remarks/>
        public klasse klasse {
            get {
                return this.klasseField;
            }
            set {
                this.klasseField = value;
            }
        }
        
        /// <remarks/>
        public saksmappe saksmappe {
            get {
                return this.saksmappeField;
            }
            set {
                this.saksmappeField = value;
            }
        }
        
        /// <remarks/>
        public journalpost journalpost {
            get {
                return this.journalpostField;
            }
            set {
                this.journalpostField = value;
            }
        }
    }
}
