//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arkivverket.Arkade.CLI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OutputStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutputStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arkivverket.Arkade.CLI.OutputStrings", typeof(OutputStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppgi test-ID (N5.XX) i starten av en egen linje for hver test som skal utføres
        ///{0} Tester kan utelates ved å sette tegnet {0} først på linjen.
        /// </summary>
        internal static string Noark5TestListDescription {
            get {
                return ResourceManager.GetString("Noark5TestListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOARK5-TESTER SOM SKAL UTFØRES AV ARKADE.
        /// </summary>
        internal static string Noark5TestListHeading {
            get {
                return ResourceManager.GetString("Noark5TestListHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{Level}] {Message}{NewLine}{Exception}.
        /// </summary>
        internal static string SystemLogOutputTemplateForConsole {
            get {
                return ResourceManager.GetString("SystemLogOutputTemplateForConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Timestamp:yyyy-MM-ddTHH:mm:ss.fff} [{Level}] {SourceContext} {Message}{NewLine}{Exception}.
        /// </summary>
        internal static string SystemLogOutputTemplateForFile {
            get {
                return ResourceManager.GetString("SystemLogOutputTemplateForFile", resourceCulture);
            }
        }
    }
}
