//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arkivverket.Arkade.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddmlMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddmlMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arkivverket.Arkade.Core.Resources.AddmlMessages", typeof(AddmlMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to required ADDML data.
        /// </summary>
        public static string Addml {
            get {
                return ResourceManager.GetString("Addml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to required ADDML file.
        /// </summary>
        public static string AddmlFile {
            get {
                return ResourceManager.GetString("AddmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to required ADDML information.
        /// </summary>
        public static string AddmlInfo {
            get {
                return ResourceManager.GetString("AddmlInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reference to {0} found. This must be defined..
        /// </summary>
        public static string AssertNotNull {
            get {
                return ResourceManager.GetString("AssertNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find {0}. This must be both defined and set to a value..
        /// </summary>
        public static string AssertNotNullOrEmpty {
            get {
                return ResourceManager.GetString("AssertNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkade does not support the specified ADDML process {0}.
        /// </summary>
        public static string CouldNotInstatiateUnsupportedAddmlProcess {
            get {
                return ResourceManager.GetString("CouldNotInstatiateUnsupportedAddmlProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDML element dataset.
        /// </summary>
        public static string Dataset {
            get {
                return ResourceManager.GetString("Dataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDML record with incorrect number of fields in file {0}, record number {1}, error number {2}.
        /// </summary>
        public static string FailedRecordErrorIdentifier {
            get {
                return ResourceManager.GetString("FailedRecordErrorIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Field text: {1}.
        /// </summary>
        public static string FailedRecordErrorMessage {
            get {
                return ResourceManager.GetString("FailedRecordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDML element flatFileDefinitions.
        /// </summary>
        public static string FlatFileDefinitions {
            get {
                return ResourceManager.GetString("FlatFileDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDML element flatFiles.
        /// </summary>
        public static string FlatFiles {
            get {
                return ResourceManager.GetString("FlatFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDML records with incorrect number of fields in file {0}.
        /// </summary>
        public static string NumberOfRecordsWithFieldDelimiterErrorIdentifier {
            get {
                return ResourceManager.GetString("NumberOfRecordsWithFieldDelimiterErrorIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDML element recordDefinitions.
        /// </summary>
        public static string RecordDefinitions {
            get {
                return ResourceManager.GetString("RecordDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDML record with incorrect number of fields.
        /// </summary>
        public static string RecordLengthErrorTestName {
            get {
                return ResourceManager.GetString("RecordLengthErrorTestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file&apos;s total number of records with incorrect number of fields: {0}.
        /// </summary>
        public static string TotalAmountOfRecordsWithFieldDelimiterErrorResultText {
            get {
                return ResourceManager.GetString("TotalAmountOfRecordsWithFieldDelimiterErrorResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount: {0}.
        /// </summary>
        public static string TotalAmountText {
            get {
                return ResourceManager.GetString("TotalAmountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected field quantity (found/expected).
        /// </summary>
        public static string UnexpectedNumberOfFields {
            get {
                return ResourceManager.GetString("UnexpectedNumberOfFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown ADDML process: {0}.
        /// </summary>
        public static string UnknownAddmlProcess {
            get {
                return ResourceManager.GetString("UnknownAddmlProcess", resourceCulture);
            }
        }
    }
}
