//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arkivverket.Arkade.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormatAnalysisResultFileContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormatAnalysisResultFileContent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arkivverket.Arkade.Core.Resources.FormatAnalysisResultFileContent", typeof(FormatAnalysisResultFileContent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string HeaderErrors {
            get {
                return ResourceManager.GetString("HeaderErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension.
        /// </summary>
        public static string HeaderFileExtension {
            get {
                return ResourceManager.GetString("HeaderFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string HeaderFileName {
            get {
                return ResourceManager.GetString("HeaderFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format ID.
        /// </summary>
        public static string HeaderFormatId {
            get {
                return ResourceManager.GetString("HeaderFormatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format name.
        /// </summary>
        public static string HeaderFormatName {
            get {
                return ResourceManager.GetString("HeaderFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format version.
        /// </summary>
        public static string HeaderFormatVersion {
            get {
                return ResourceManager.GetString("HeaderFormatVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIME type.
        /// </summary>
        public static string HeaderMimeType {
            get {
                return ResourceManager.GetString("HeaderMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string StatisticsHeaderAmount {
            get {
                return ResourceManager.GetString("StatisticsHeaderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type.
        /// </summary>
        public static string StatisticsHeaderFileType {
            get {
                return ResourceManager.GetString("StatisticsHeaderFileType", resourceCulture);
            }
        }
    }
}
