//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arkivverket.Arkade.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arkivverket.Arkade.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs a frequency analysis on all fields with a defined codeset.
        /// </summary>
        public static string AnalyseAllFrequenceListDescription {
            get {
                return ResourceManager.GetString("AnalyseAllFrequenceListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} occurrences of {1}.
        /// </summary>
        public static string AnalyseAllFrequenceListMessage {
            get {
                return ResourceManager.GetString("AnalyseAllFrequenceListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts the number of characters in a file.
        /// </summary>
        public static string AnalyseCountCharsDescription {
            get {
                return ResourceManager.GetString("AnalyseCountCharsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} characters.
        /// </summary>
        public static string AnalyseCountCharsMessage {
            get {
                return ResourceManager.GetString("AnalyseCountCharsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts the number of occurrences of null in the field.
        /// </summary>
        public static string AnalyseCountNullDescription {
            get {
                return ResourceManager.GetString("AnalyseCountNullDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} occurrences of null.
        /// </summary>
        public static string AnalyseCountNullMessage {
            get {
                return ResourceManager.GetString("AnalyseCountNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts the number of records for each record type.
        /// </summary>
        public static string AnalyseCountRecordDefinitionOccurrencesDescription {
            get {
                return ResourceManager.GetString("AnalyseCountRecordDefinitionOccurrencesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} records.
        /// </summary>
        public static string AnalyseCountRecordDefinitionOccurrencesMessage {
            get {
                return ResourceManager.GetString("AnalyseCountRecordDefinitionOccurrencesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts the number of records in a file.
        /// </summary>
        public static string AnalyseCountRecordsDescription {
            get {
                return ResourceManager.GetString("AnalyseCountRecordsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0} records.
        /// </summary>
        public static string AnalyseCountRecordsMessage {
            get {
                return ResourceManager.GetString("AnalyseCountRecordsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds the longest and shortest record for each record type.
        /// </summary>
        public static string AnalyseFindExtremeRecordsDescription {
            get {
                return ResourceManager.GetString("AnalyseFindExtremeRecordsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest/shortest record: {0}/{1}.
        /// </summary>
        public static string AnalyseFindExtremeRecordsMessage {
            get {
                return ResourceManager.GetString("AnalyseFindExtremeRecordsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds the longest and shortest value in the field.
        /// </summary>
        public static string AnalyseFindExtremeValuesDescription {
            get {
                return ResourceManager.GetString("AnalyseFindExtremeValuesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest/shortest value: {0}/{1}.
        /// </summary>
        public static string AnalyseFindExtremeValuesMessage {
            get {
                return ResourceManager.GetString("AnalyseFindExtremeValuesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds the lowest and highest value in the field.
        /// </summary>
        public static string AnalyseFindMinMaxValuesDescription {
            get {
                return ResourceManager.GetString("AnalyseFindMinMaxValuesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest/highest value: {0}/{1}.
        /// </summary>
        public static string AnalyseFindMinMaxValuesMessage {
            get {
                return ResourceManager.GetString("AnalyseFindMinMaxValuesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts the number of occurrences of each value in the field.
        /// </summary>
        public static string AnalyseFrequenceListDescription {
            get {
                return ResourceManager.GetString("AnalyseFrequenceListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} occurrences of {1}.
        /// </summary>
        public static string AnalyseFrequenceListMessage {
            get {
                return ResourceManager.GetString("AnalyseFrequenceListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control of control digits in an account number.
        /// </summary>
        public static string ControlAccountNumberDescription {
            get {
                return ResourceManager.GetString("ControlAccountNumberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid account number: {0}.
        /// </summary>
        public static string ControlAccountNumberMessage {
            get {
                return ResourceManager.GetString("ControlAccountNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validates given record lengths for all record types (fixed format only).
        /// </summary>
        public static string ControlAllFixedLengthDescription {
            get {
                return ResourceManager.GetString("ControlAllFixedLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatch between given record length ({0}) and actual record length ({1}).
        /// </summary>
        public static string ControlAllFixedLengthMessage {
            get {
                return ResourceManager.GetString("ControlAllFixedLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation of the control digits in a birth number.
        /// </summary>
        public static string ControlBirthNumberDescription {
            get {
                return ResourceManager.GetString("ControlBirthNumberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid birth number: {0}.
        /// </summary>
        public static string ControlBirthNumberMessage {
            get {
                return ResourceManager.GetString("ControlBirthNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validates values in a boolean field.
        /// </summary>
        public static string ControlBooleanValueDescription {
            get {
                return ResourceManager.GetString("ControlBooleanValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found non-boolean values: {0}.
        /// </summary>
        public static string ControlBooleanValueMessage {
            get {
                return ResourceManager.GetString("ControlBooleanValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum validation.
        /// </summary>
        public static string ControlChecksumDescription {
            get {
                return ResourceManager.GetString("ControlChecksumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected checksum: {0}
        ///Actual checksum: {1}.
        /// </summary>
        public static string ControlChecksumMessage_ChecksumMismatch {
            get {
                return ResourceManager.GetString("ControlChecksumMessage_ChecksumMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No checksum found in the ADDML file.
        /// </summary>
        public static string ControlChecksumMessage_ChecksumMissing {
            get {
                return ResourceManager.GetString("ControlChecksumMessage_ChecksumMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown checksum algorithm: {0}.
        /// </summary>
        public static string ControlChecksumMessage_UnknownChecksumAlgorithm {
            get {
                return ResourceManager.GetString("ControlChecksumMessage_UnknownChecksumAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validates that defined codes are used, and that used codes are defined in the codelist.
        /// </summary>
        public static string ControlCodesDescription {
            get {
                return ResourceManager.GetString("ControlCodesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used codes not present in the codelist: {0}.
        /// </summary>
        public static string ControlCodesMessage {
            get {
                return ResourceManager.GetString("ControlCodesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validates given data format.
        /// </summary>
        public static string ControlDataFormatDescription {
            get {
                return ResourceManager.GetString("ControlDataFormatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data format: {0}.
        /// </summary>
        public static string ControlDataFormatMessage {
            get {
                return ResourceManager.GetString("ControlDataFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  + {0} more.
        /// </summary>
        public static string ControlDataFormatMessageExtension {
            get {
                return ResourceManager.GetString("ControlDataFormatMessageExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation of date-field values.
        /// </summary>
        public static string ControlDateValueDescription {
            get {
                return ResourceManager.GetString("ControlDateValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values not validated as date: {0}.
        /// </summary>
        public static string ControlDateValueMessage {
            get {
                return ResourceManager.GetString("ControlDateValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks that existing files are defined in ADDML, and that files defined in ADDML are existing.
        /// </summary>
        public static string ControlExtraOrMissingFilesDescription {
            get {
                return ResourceManager.GetString("ControlExtraOrMissingFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present in ADDML but missing from archive.
        /// </summary>
        public static string ControlExtraOrMissingFilesMessage1 {
            get {
                return ResourceManager.GetString("ControlExtraOrMissingFilesMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present in archive but missing from ADDML.
        /// </summary>
        public static string ControlExtraOrMissingFilesMessage2 {
            get {
                return ResourceManager.GetString("ControlExtraOrMissingFilesMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validates given record length (fixed format only).
        /// </summary>
        public static string ControlFixedLengthDescription {
            get {
                return ResourceManager.GetString("ControlFixedLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatch between given record length ({0}) and actual record length ({1}).
        /// </summary>
        public static string ControlFixedLengthMessage {
            get {
                return ResourceManager.GetString("ControlFixedLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validates foreign keys.
        /// </summary>
        public static string ControlForeignKeyDescription {
            get {
                return ResourceManager.GetString("ControlForeignKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid foreign key: The value [{0}] does not exist in the referred field {1}.
        /// </summary>
        public static string ControlForeignKeyMessage1 {
            get {
                return ResourceManager.GetString("ControlForeignKeyMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid foreign key: The values [{0}] does not exist in the referred fields {1}.
        /// </summary>
        public static string ControlForeignKeyMessage1Combined {
            get {
                return ResourceManager.GetString("ControlForeignKeyMessage1Combined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid foreign key: Can not find any values for the field {0}.
        /// </summary>
        public static string ControlForeignKeyMessage2 {
            get {
                return ResourceManager.GetString("ControlForeignKeyMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validates uniqueness of the key (primary eller alternate).
        /// </summary>
        public static string ControlKeyDescription {
            get {
                return ResourceManager.GetString("ControlKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following primary key values are not unique: {0}.
        /// </summary>
        public static string ControlKeyMessage {
            get {
                return ResourceManager.GetString("ControlKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks whether the stated maximum length is actually the largest length in the field.
        /// </summary>
        public static string ControlMaxLengthDescription {
            get {
                return ResourceManager.GetString("ControlMaxLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values longer than the maximum length: {0}.
        /// </summary>
        public static string ControlMaxLengthMessage {
            get {
                return ResourceManager.GetString("ControlMaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks whether the stated minimum length is actually the smallest length in the field.
        /// </summary>
        public static string ControlMinLengthDescription {
            get {
                return ResourceManager.GetString("ControlMinLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values smaller than the minimum length: {0}.
        /// </summary>
        public static string ControlMinLengthMessage {
            get {
                return ResourceManager.GetString("ControlMinLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks the field for null-values.
        /// </summary>
        public static string ControlNotNullDescription {
            get {
                return ResourceManager.GetString("ControlNotNullDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL values exists.
        /// </summary>
        public static string ControlNotNullMessage {
            get {
                return ResourceManager.GetString("ControlNotNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks if this record type is used in the dataset.
        /// </summary>
        public static string ControlNotUsedRecordDefDescription {
            get {
                return ResourceManager.GetString("ControlNotUsedRecordDefDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record type is not in use.
        /// </summary>
        public static string ControlNotUsedRecordDefMessage {
            get {
                return ResourceManager.GetString("ControlNotUsedRecordDefMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts and checks that the number of records in the file is equal to the number specified in the numberOfRecords property in flatFile.
        /// </summary>
        public static string ControlNumberOfRecordsDescription {
            get {
                return ResourceManager.GetString("ControlNumberOfRecordsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected number of records not specified. Unable to control number of records.
        /// </summary>
        public static string ControlNumberOfRecordsMessage1 {
            get {
                return ResourceManager.GetString("ControlNumberOfRecordsMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of records ({0}) matched.
        /// </summary>
        public static string ControlNumberOfRecordsMessage2 {
            get {
                return ResourceManager.GetString("ControlNumberOfRecordsMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of records did not match. Expected {0}, found {1}.
        /// </summary>
        public static string ControlNumberOfRecordsMessage3 {
            get {
                return ResourceManager.GetString("ControlNumberOfRecordsMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation of the control digits in an organisation number.
        /// </summary>
        public static string ControlOrganizationNumberDescription {
            get {
                return ResourceManager.GetString("ControlOrganizationNumberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid organisation number: {0}.
        /// </summary>
        public static string ControlOrganizationNumberMessage {
            get {
                return ResourceManager.GetString("ControlOrganizationNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validates uniqueness of the values in the field.
        /// </summary>
        public static string ControlUniquenessDescription {
            get {
                return ResourceManager.GetString("ControlUniquenessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All values are unique.
        /// </summary>
        public static string ControlUniquenessMessage1 {
            get {
                return ResourceManager.GetString("ControlUniquenessMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all values are unique.
        /// </summary>
        public static string ControlUniquenessMessage2 {
            get {
                return ResourceManager.GetString("ControlUniquenessMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: The number of characters in the FixedLength field [{1}] does not match the number of characters summed for the record definition [{2}]..
        /// </summary>
        public static string ExceptionFixedLengthSumIsNotCorrect {
            get {
                return ResourceManager.GetString("ExceptionFixedLengthSumIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading ADDML.
        ///{0}.
        /// </summary>
        public static string ExceptionReadingAddmlFile {
            get {
                return ResourceManager.GetString("ExceptionReadingAddmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing of archive completed..
        /// </summary>
        public static string LogMessageFinishedTesting {
            get {
                return ResourceManager.GetString("LogMessageFinishedTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting testing of archive..
        /// </summary>
        public static string LogMessageStartTesting {
            get {
                return ResourceManager.GetString("LogMessageStartTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of the number of records with errors associated with field separator and/or record separator..
        /// </summary>
        public static string NumberOfRecordsWithFieldDelimiterErrorDescription {
            get {
                return ResourceManager.GetString("NumberOfRecordsWithFieldDelimiterErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading archive.
        /// </summary>
        public static string ReadingArchiveEvent {
            get {
                return ResourceManager.GetString("ReadingArchiveEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive is loaded..
        /// </summary>
        public static string ReadingArchiveEventFinishedMessage {
            get {
                return ResourceManager.GetString("ReadingArchiveEventFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDML processes on the file: {0}.
        /// </summary>
        public static string RunningAddmlProcessesOnFile {
            get {
                return ResourceManager.GetString("RunningAddmlProcessesOnFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive extraction.
        /// </summary>
        public static string TarExtractionEvent {
            get {
                return ResourceManager.GetString("TarExtractionEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive is extracted to {0}.
        /// </summary>
        public static string TarExtractionMessageFinished {
            get {
                return ResourceManager.GetString("TarExtractionMessageFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting extraction..
        /// </summary>
        public static string TarExtractionMessageStarted {
            get {
                return ResourceManager.GetString("TarExtractionMessageStarted", resourceCulture);
            }
        }
    }
}
