//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arkivverket.Arkade.GUI.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AboutGUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutGUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arkivverket.Arkade.GUI.Resources.AboutGUI", typeof(AboutGUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string AboutDialogCloseButtonText {
            get {
                return ResourceManager.GetString("AboutDialogCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkade 5.
        /// </summary>
        public static string AboutDialogHeaderText {
            get {
                return ResourceManager.GetString("AboutDialogHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Arkade 5.
        /// </summary>
        public static string AboutDialogWindowName {
            get {
                return ResourceManager.GetString("AboutDialogWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.apache.org/licenses/LICENSE-2.0.
        /// </summary>
        public static string ApacheV2_0Uri {
            get {
                return ResourceManager.GetString("ApacheV2_0Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © {0} Arkivverket. Licensed under.
        /// </summary>
        public static string ArkadeCopyrightInformationText {
            get {
                return ResourceManager.GetString("ArkadeCopyrightInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkade 5 uses.
        /// </summary>
        public static string BundledSoftwareInformation_1 {
            get {
                return ResourceManager.GetString("BundledSoftwareInformation_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siegfried.
        /// </summary>
        public static string BundledSoftwareInformation_2 {
            get {
                return ResourceManager.GetString("BundledSoftwareInformation_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Copyright © 2019 Richard Lehane), licensed under.
        /// </summary>
        public static string BundledSoftwareInformation_3 {
            get {
                return ResourceManager.GetString("BundledSoftwareInformation_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to perform format analysis..
        /// </summary>
        public static string BundledSoftwareInformation_5 {
            get {
                return ResourceManager.GetString("BundledSoftwareInformation_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.gnu.org/licenses/gpl-3.0.en.html.
        /// </summary>
        public static string GnuGpl3_0Uri {
            get {
                return ResourceManager.GetString("GnuGpl3_0Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apache License, Version 2.0.
        /// </summary>
        public static string LicenseApache2_0 {
            get {
                return ResourceManager.GetString("LicenseApache2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNU GPL v3.0.
        /// </summary>
        public static string LicenseGNU {
            get {
                return ResourceManager.GetString("LicenseGNU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.itforarchivists.com/siegfried/.
        /// </summary>
        public static string SiegfriedUri {
            get {
                return ResourceManager.GetString("SiegfriedUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
    }
}
