//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arkivverket.Arkade.GUI.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arkivverket.Arkade.GUI.Resources.GUI", typeof(GUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkade 5.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working area - {0}.
        /// </summary>
        public static string ArkadeDirectoryPathInfo {
            get {
                return ResourceManager.GetString("ArkadeDirectoryPathInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arkade-error-{0}.log.
        /// </summary>
        public static string DetailedErrorMessageFileName {
            get {
                return ResourceManager.GetString("DetailedErrorMessageFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details are written to {0}.
        /// </summary>
        public static string DetailedErrorMessageInfo {
            get {
                return ResourceManager.GetString("DetailedErrorMessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred: {0}.
        /// </summary>
        public static string ErrorGeneral {
            get {
                return ResourceManager.GetString("ErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when loading archive: {0}.
        /// </summary>
        public static string ErrorReadingArchive {
            get {
                return ResourceManager.GetString("ErrorReadingArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred with the chosen file.
        /// </summary>
        public static string FileException_ErrorWithChosenFile {
            get {
                return ResourceManager.GetString("FileException_ErrorWithChosenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A general error occurred when choosing a file.
        /// </summary>
        public static string FileException_GeneralError {
            get {
                return ResourceManager.GetString("FileException_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file was chosen.
        /// </summary>
        public static string FileException_NoFileChosen {
            get {
                return ResourceManager.GetString("FileException_NoFileChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: {0}.
        /// </summary>
        public static string FileNotFoundMessage {
            get {
                return ResourceManager.GetString("FileNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an archive file.
        /// </summary>
        public static string FileSelectionWindowNameArchive {
            get {
                return ResourceManager.GetString("FileSelectionWindowNameArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkade 5.
        /// </summary>
        public static string General_WindowTitle {
            get {
                return ResourceManager.GetString("General_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New session.
        /// </summary>
        public static string NewProgramSessionButton {
            get {
                return ResourceManager.GetString("NewProgramSessionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available.
        /// </summary>
        public static string NewVersionMessage {
            get {
                return ResourceManager.GetString("NewVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Arkade.
        /// </summary>
        public static string RestartArkadeButtonText {
            get {
                return ResourceManager.GetString("RestartArkadeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting of Arkade.
        /// </summary>
        public static string RestartArkadeDialogTitle {
            get {
                return ResourceManager.GetString("RestartArkadeDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkade needs to be restarted for the changes to be applied. Do you want to do the restart now?.
        /// </summary>
        public static string RestartArkadeForChangesToTakeEffectPrompt {
            get {
                return ResourceManager.GetString("RestartArkadeForChangesToTakeEffectPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not restart Arkade.
        ///Please manually start Arkade after shutdown..
        /// </summary>
        public static string RestartFailedMessageBoxText {
            get {
                return ResourceManager.GetString("RestartFailedMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic restart failed.
        /// </summary>
        public static string RestartFailedMessageBoxTitle {
            get {
                return ResourceManager.GetString("RestartFailedMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Timestamp:yyyy-MM-ddTHH:mm:ss.fff} [{Level}] {SourceContext} {Message}{NewLine}{Exception}.
        /// </summary>
        public static string SerilogFormatConfig {
            get {
                return ResourceManager.GetString("SerilogFormatConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om Arkade 5.
        /// </summary>
        public static string ShowAboutDialogButtonText {
            get {
                return ResourceManager.GetString("ShowAboutDialogButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ShowSettingsDialogButtonText {
            get {
                return ResourceManager.GetString("ShowSettingsDialogButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string ShowToolsDialogButtonText {
            get {
                return ResourceManager.GetString("ShowToolsDialogButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web page.
        /// </summary>
        public static string ShowWebPageButtonText {
            get {
                return ResourceManager.GetString("ShowWebPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output language: {0}.
        /// </summary>
        public static string UiAndOutputLanguagesIsDifferentWarningMessage {
            get {
                return ResourceManager.GetString("UiAndOutputLanguagesIsDifferentWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the application is closed now, the current test results will be lost. Do you still want to close?.
        /// </summary>
        public static string UnsavedTestResultsOnExitWarning {
            get {
                return ResourceManager.GetString("UnsavedTestResultsOnExitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version .
        /// </summary>
        public static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
    }
}
