//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arkivverket.Arkade.GUI.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetaDataGUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetaDataGUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arkivverket.Arkade.GUI.Resources.MetaDataGUI", typeof(MetaDataGUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Number*.
        /// </summary>
        public static string AgreementNumber {
            get {
                return ResourceManager.GetString("AgreementNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Creator*.
        /// </summary>
        public static string ArchiveCreator {
            get {
                return ResourceManager.GetString("ArchiveCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (Contact, Archive Creator).
        /// </summary>
        public static string ArchiveCreator_Address {
            get {
                return ResourceManager.GetString("ArchiveCreator_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person (Archive Creator).
        /// </summary>
        public static string ArchiveCreator_ContactPerson {
            get {
                return ResourceManager.GetString("ArchiveCreator_ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail (Contact, Archive Creator).
        /// </summary>
        public static string ArchiveCreator_Email {
            get {
                return ResourceManager.GetString("ArchiveCreator_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone (Contact, Archive Creator).
        /// </summary>
        public static string ArchiveCreator_Telephone {
            get {
                return ResourceManager.GetString("ArchiveCreator_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Description.
        /// </summary>
        public static string ArchiveDescription {
            get {
                return ResourceManager.GetString("ArchiveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Extraction System.
        /// </summary>
        public static string ArchiveExtractionSystem {
            get {
                return ResourceManager.GetString("ArchiveExtractionSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type (Extract).
        /// </summary>
        public static string ArchiveExtractionType {
            get {
                return ResourceManager.GetString("ArchiveExtractionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Version (Extract).
        /// </summary>
        public static string ArchiveExtractionTypeVersion {
            get {
                return ResourceManager.GetString("ArchiveExtractionTypeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version (Extract).
        /// </summary>
        public static string ArchiveExtractionVersion {
            get {
                return ResourceManager.GetString("ArchiveExtractionVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction System.
        /// </summary>
        public static string ArchiveSystem {
            get {
                return ResourceManager.GetString("ArchiveSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include format information for document files.
        /// </summary>
        public static string CreateDocumentFileInfoText {
            get {
                return ResourceManager.GetString("CreateDocumentFileInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NB! Time consuming when many document files..
        /// </summary>
        public static string CreateDocumentFileInfoToolTip {
            get {
                return ResourceManager.GetString("CreateDocumentFileInfoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include format information for LOBs.
        /// </summary>
        public static string CreateLobFormatInfoFileText {
            get {
                return ResourceManager.GetString("CreateLobFormatInfoFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator of information package.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (Contact, Package Creator).
        /// </summary>
        public static string Creator_Address {
            get {
                return ResourceManager.GetString("Creator_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person (Package Creator).
        /// </summary>
        public static string Creator_ContactPerson {
            get {
                return ResourceManager.GetString("Creator_ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail (Contact, Package Creator).
        /// </summary>
        public static string Creator_Email {
            get {
                return ResourceManager.GetString("Creator_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original System:.
        /// </summary>
        public static string Creator_OriginalSystem {
            get {
                return ResourceManager.GetString("Creator_OriginalSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System:.
        /// </summary>
        public static string Creator_System {
            get {
                return ResourceManager.GetString("Creator_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone (Contact, Archive Creator).
        /// </summary>
        public static string Creator_Telephone {
            get {
                return ResourceManager.GetString("Creator_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction Date.
        /// </summary>
        public static string ExtractionDate {
            get {
                return ResourceManager.GetString("ExtractionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Creator.
        /// </summary>
        public static string GuiSubsection_ArchiveCreator {
            get {
                return ResourceManager.GetString("GuiSubsection_ArchiveCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of archive.
        /// </summary>
        public static string GuiSubsection_ArchiveMain {
            get {
                return ResourceManager.GetString("GuiSubsection_ArchiveMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction System.
        /// </summary>
        public static string GuiSubsection_ArchiveSystem {
            get {
                return ResourceManager.GetString("GuiSubsection_ArchiveSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator of information package.
        /// </summary>
        public static string GuiSubsection_Creator {
            get {
                return ResourceManager.GetString("GuiSubsection_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction Date.
        /// </summary>
        public static string GuiSubsection_ExtractionDate {
            get {
                return ResourceManager.GetString("GuiSubsection_ExtractionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noark fields.
        /// </summary>
        public static string GuiSubsection_NoarkParameters {
            get {
                return ResourceManager.GetString("GuiSubsection_NoarkParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string GuiSubsection_Owner {
            get {
                return ResourceManager.GetString("GuiSubsection_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer.
        /// </summary>
        public static string GuiSubsection_Producer {
            get {
                return ResourceManager.GetString("GuiSubsection_Producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient.
        /// </summary>
        public static string GuiSubsection_Recipient {
            get {
                return ResourceManager.GetString("GuiSubsection_Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string GuiSubsection_System {
            get {
                return ResourceManager.GetString("GuiSubsection_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferer.
        /// </summary>
        public static string GuiSubsection_Transferer {
            get {
                return ResourceManager.GetString("GuiSubsection_Transferer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current system name, start year and end year.
        /// </summary>
        public static string Label_HintTextStandardLabel {
            get {
                return ResourceManager.GetString("Label_HintTextStandardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded or given value.
        /// </summary>
        public static string Label_HintTextUserdefinedLabel {
            get {
                return ResourceManager.GetString("Label_HintTextUserdefinedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Label_OptionTextStandardLabel {
            get {
                return ResourceManager.GetString("Label_OptionTextStandardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Label_OptionTextUserdefinedLabel {
            get {
                return ResourceManager.GetString("Label_OptionTextUserdefinedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch external metadata.
        /// </summary>
        public static string LoadExternalMetadataButtonText {
            get {
                return ResourceManager.GetString("LoadExternalMetadataButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out the form with metadata from an external METS-file, e.g. info.xml from a previously created package..
        /// </summary>
        public static string LoadExternalMetadataInfoText {
            get {
                return ResourceManager.GetString("LoadExternalMetadataInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string MetadataGuiLocale {
            get {
                return ResourceManager.GetString("MetadataGuiLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was not able to fetch metadata from {0}.
        /// </summary>
        public static string MetadataLoadError {
            get {
                return ResourceManager.GetString("MetadataLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * = Required field for creating a valid archive package.
        /// </summary>
        public static string MetadataRequiredFieldsInfo {
            get {
                return ResourceManager.GetString("MetadataRequiredFieldsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner*.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (Contact, Owner).
        /// </summary>
        public static string Owner_Address {
            get {
                return ResourceManager.GetString("Owner_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person (Owner).
        /// </summary>
        public static string Owner_ContactPerson {
            get {
                return ResourceManager.GetString("Owner_ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail (Contact, Owner).
        /// </summary>
        public static string Owner_Email {
            get {
                return ResourceManager.GetString("Owner_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone (Contact, Owner).
        /// </summary>
        public static string Owner_Telephone {
            get {
                return ResourceManager.GetString("Owner_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create/overwite package. Please make sure the package location is not busy..
        /// </summary>
        public static string PackageCreationErrorStatusMessage {
            get {
                return ResourceManager.GetString("PackageCreationErrorStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating package....
        /// </summary>
        public static string PackageCreationOngoing {
            get {
                return ResourceManager.GetString("PackageCreationOngoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer*.
        /// </summary>
        public static string Producer {
            get {
                return ResourceManager.GetString("Producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (Contact, Producer).
        /// </summary>
        public static string Producer_Address {
            get {
                return ResourceManager.GetString("Producer_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person (Producer).
        /// </summary>
        public static string Producer_ContactPerson {
            get {
                return ResourceManager.GetString("Producer_ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail  (Contact, Producer).
        /// </summary>
        public static string Producer_Email {
            get {
                return ResourceManager.GetString("Producer_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone  (Contact, Producer).
        /// </summary>
        public static string Producer_Telephone {
            get {
                return ResourceManager.GetString("Producer_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient*.
        /// </summary>
        public static string Recipient {
            get {
                return ResourceManager.GetString("Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose METS-file to load metadata.
        /// </summary>
        public static string SelectMetadataFile {
            get {
                return ResourceManager.GetString("SelectMetadataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose package location.
        /// </summary>
        public static string SelectOutputDirectoryMessage {
            get {
                return ResourceManager.GetString("SelectOutputDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Name*.
        /// </summary>
        public static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type (System)*.
        /// </summary>
        public static string SystemType {
            get {
                return ResourceManager.GetString("SystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Version (System).
        /// </summary>
        public static string SystemTypeVersion {
            get {
                return ResourceManager.GetString("SystemTypeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version (System)*.
        /// </summary>
        public static string SystemVersion {
            get {
                return ResourceManager.GetString("SystemVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferer*.
        /// </summary>
        public static string Transferer {
            get {
                return ResourceManager.GetString("Transferer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (Contact, Transferer).
        /// </summary>
        public static string Transferer_Address {
            get {
                return ResourceManager.GetString("Transferer_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person (Transferer)*.
        /// </summary>
        public static string Transferer_ContractPerson {
            get {
                return ResourceManager.GetString("Transferer_ContractPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail (Contact, Transferer).
        /// </summary>
        public static string Transferer_Email {
            get {
                return ResourceManager.GetString("Transferer_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone (Contact, Transferer).
        /// </summary>
        public static string Transferer_Telephone {
            get {
                return ResourceManager.GetString("Transferer_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough disk space on target location..
        /// </summary>
        public static string UnsufficientDiskSpaceStatusMessage {
            get {
                return ResourceManager.GetString("UnsufficientDiskSpaceStatusMessage", resourceCulture);
            }
        }
    }
}
