//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arkivverket.Arkade.GUI.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestRunnerGUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestRunnerGUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arkivverket.Arkade.GUI.Resources.TestRunnerGUI", typeof(TestRunnerGUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The archive is not testable: A valid specification file for the extract was not found.
        ///(See log for details {0}).
        ///It can still be created a package from the extract..
        /// </summary>
        public static string ArchiveNotTestable {
            get {
                return ResourceManager.GetString("ArchiveNotTestable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testability.
        /// </summary>
        public static string ArchiveTestability {
            get {
                return ResourceManager.GetString("ArchiveTestability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create package.
        /// </summary>
        public static string CreatePackageButtonText {
            get {
                return ResourceManager.GetString("CreatePackageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details are written to {0}.
        /// </summary>
        public static string DetailedErrorMessageInfo {
            get {
                return ResourceManager.GetString("DetailedErrorMessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading archive: {0}.
        /// </summary>
        public static string ErrorReadingArchive {
            get {
                return ResourceManager.GetString("ErrorReadingArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating report.
        /// </summary>
        public static string EventIdCreatingReport {
            get {
                return ResourceManager.GetString("EventIdCreatingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing completed.
        /// </summary>
        public static string EventIdFinishedOperation {
            get {
                return ResourceManager.GetString("EventIdFinishedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while testing.
        /// </summary>
        public static string EventIdFinishedWithError {
            get {
                return ResourceManager.GetString("EventIdFinishedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: {0}.
        /// </summary>
        public static string FileNotFoundMessage {
            get {
                return ResourceManager.GetString("FileNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive type:.
        /// </summary>
        public static string HeaderArchiveType {
            get {
                return ResourceManager.GetString("HeaderArchiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to file:.
        /// </summary>
        public static string HeaderFilePath {
            get {
                return ResourceManager.GetString("HeaderFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of files processed:.
        /// </summary>
        public static string HeaderNumberOfProcessedFiles {
            get {
                return ResourceManager.GetString("HeaderNumberOfProcessedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of posts processed:.
        /// </summary>
        public static string HeaderNumberofProcessedPosts {
            get {
                return ResourceManager.GetString("HeaderNumberofProcessedPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of XML elements processed:.
        /// </summary>
        public static string HeaderNumberOfProcessedXmlElements {
            get {
                return ResourceManager.GetString("HeaderNumberOfProcessedXmlElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing file:.
        /// </summary>
        public static string HeaderProcessingFile {
            get {
                return ResourceManager.GetString("HeaderProcessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UUID:.
        /// </summary>
        public static string HeaderUUID {
            get {
                return ResourceManager.GetString("HeaderUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageLabelError {
            get {
                return ResourceManager.GetString("MessageLabelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NB!.
        /// </summary>
        public static string MessageLabelInfo {
            get {
                return ResourceManager.GetString("MessageLabelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MessageLabelSuccess {
            get {
                return ResourceManager.GetString("MessageLabelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MessageLabelWarning {
            get {
                return ResourceManager.GetString("MessageLabelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New session.
        /// </summary>
        public static string NewProgramSessionButtonText {
            get {
                return ResourceManager.GetString("NewProgramSessionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show report.
        /// </summary>
        public static string ShowTestReportButtonText {
            get {
                return ResourceManager.GetString("ShowTestReportButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance testing for Siard extracts is not supported. Format analysis for BLOBs/CLOBs in the extract is available upon creation of package..
        /// </summary>
        public static string SiardSupportInfo {
            get {
                return ResourceManager.GetString("SiardSupportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start testing.
        /// </summary>
        public static string StartTestingButtonText {
            get {
                return ResourceManager.GetString("StartTestingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing of {0} extracts is not available.
        /// </summary>
        public static string TestingNotImplemented {
            get {
                return ResourceManager.GetString("TestingNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages:.
        /// </summary>
        public static string TestMessagesHeading {
            get {
                return ResourceManager.GetString("TestMessagesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report saved {0}.
        /// </summary>
        public static string TestReportIsSavedMessage {
            get {
                return ResourceManager.GetString("TestReportIsSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose all/none.
        /// </summary>
        public static string TestSelectionChooseAllOrNoneCheckBoxText {
            get {
                return ResourceManager.GetString("TestSelectionChooseAllOrNoneCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests (expand for selection).
        /// </summary>
        public static string TestSelectionHeader {
            get {
                return ResourceManager.GetString("TestSelectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive extract testing.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
