//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arkivverket.Arkade.GUI.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ToolsGUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolsGUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arkivverket.Arkade.GUI.Resources.ToolsGUI", typeof(ToolsGUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose directory ....
        /// </summary>
        public static string ArchiveFormatValidationChooseDirectoryButtonText {
            get {
                return ResourceManager.GetString("ArchiveFormatValidationChooseDirectoryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file ....
        /// </summary>
        public static string ArchiveFormatValidationChooseFileButtonText {
            get {
                return ResourceManager.GetString("ArchiveFormatValidationChooseFileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a directory whose content to validate.
        /// </summary>
        public static string ArchiveFormatValidationDirectorySelectDialogTitle {
            get {
                return ResourceManager.GetString("ArchiveFormatValidationDirectorySelectDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive format files (*.pdf;*.tar)|*.pdf;*.tar.
        /// </summary>
        public static string ArchiveFormatValidationFileSelectDialogFilter {
            get {
                return ResourceManager.GetString("ArchiveFormatValidationFileSelectDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a file to validate.
        /// </summary>
        public static string ArchiveFormatValidationFileSelectDialogTitle {
            get {
                return ResourceManager.GetString("ArchiveFormatValidationFileSelectDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive format.
        /// </summary>
        public static string ArchiveFormatValidationFormatSelectMenuLabel {
            get {
                return ResourceManager.GetString("ArchiveFormatValidationFormatSelectMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string ArchiveFormatValidationRunButtonText {
            get {
                return ResourceManager.GetString("ArchiveFormatValidationRunButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing archive format validation ....
        /// </summary>
        public static string ArchiveFormatValidationRunningStatusMessage {
            get {
                return ResourceManager.GetString("ArchiveFormatValidationRunningStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive format validation.
        /// </summary>
        public static string ArchiveFormatValidationSectionHeading {
            get {
                return ResourceManager.GetString("ArchiveFormatValidationSectionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (calculating..).
        /// </summary>
        public static string Calculating {
            get {
                return ResourceManager.GetString("Calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose directory with the content to be analysed.
        /// </summary>
        public static string ChooseDirectoryToAnalyse {
            get {
                return ResourceManager.GetString("ChooseDirectoryToAnalyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseDialogButtonText {
            get {
                return ResourceManager.GetString("CloseDialogButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to format analysis.
        /// </summary>
        public static string FormatAnalysis {
            get {
                return ResourceManager.GetString("FormatAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRONOM analysis errors.
        /// </summary>
        public static string FormatAnalysisFailedMessageBoxCaption {
            get {
                return ResourceManager.GetString("FormatAnalysisFailedMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The analysis failed for the following targets:
        ///{0}.
        /// </summary>
        public static string FormatAnalysisFailedMessageBoxText {
            get {
                return ResourceManager.GetString("FormatAnalysisFailedMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose directory ....
        /// </summary>
        public static string FormatCheckChooseTargetDirectoryButtonText {
            get {
                return ResourceManager.GetString("FormatCheckChooseTargetDirectoryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format analysis completed!
        ///Result saved at:.
        /// </summary>
        public static string FormatCheckCompletedMessage {
            get {
                return ResourceManager.GetString("FormatCheckCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRONOM file format analysis.
        /// </summary>
        public static string FormatCheckHeading {
            get {
                return ResourceManager.GetString("FormatCheckHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing format analysis: {0}.
        /// </summary>
        public static string FormatCheckOngoing {
            get {
                return ResourceManager.GetString("FormatCheckOngoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose location for results.
        /// </summary>
        public static string FormatCheckOutputDirectoryPickerTitle {
            get {
                return ResourceManager.GetString("FormatCheckOutputDirectoryPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string FormatCheckRunButtonText {
            get {
                return ResourceManager.GetString("FormatCheckRunButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata example file was generated:.
        /// </summary>
        public static string GenerateMetadataExampleFilePathLabel {
            get {
                return ResourceManager.GetString("GenerateMetadataExampleFilePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string MetadataExampleFileGenerationRunButtonText {
            get {
                return ResourceManager.GetString("MetadataExampleFileGenerationRunButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose name and location for metadata example file.
        /// </summary>
        public static string MetadataExampleFileGenerationSaveFileDialogTitle {
            get {
                return ResourceManager.GetString("MetadataExampleFileGenerationSaveFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create metadata example file.
        /// </summary>
        public static string MetadataExampleFileGenerationSectionHeading {
            get {
                return ResourceManager.GetString("MetadataExampleFileGenerationSectionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF/A validation.
        /// </summary>
        public static string PdfAValidation {
            get {
                return ResourceManager.GetString("PdfAValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkade encountered an error which caused &apos;{0}&apos; to abort. Please see log for details..
        /// </summary>
        public static string ProcessFailedMessage {
            get {
                return ResourceManager.GetString("ProcessFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV (Comma separated values) (*.csv)|*.csv.
        /// </summary>
        public static string SaveFormatFileExtensionFilter {
            get {
                return ResourceManager.GetString("SaveFormatFileExtensionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string ToolsDialogTitle {
            get {
                return ResourceManager.GetString("ToolsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the Tools dialog is closed now, results from {0} will be lost. Do you still want to close?.
        /// </summary>
        public static string UnsavedResultsOnExitWarning {
            get {
                return ResourceManager.GetString("UnsavedResultsOnExitWarning", resourceCulture);
            }
        }
    }
}
