//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arkivverket.Arkade.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arkivverket.Arkade.UI.Resources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opprett pakke.
        /// </summary>
        public static string CreatePackageButtonText {
            get {
                return ResourceManager.GetString("CreatePackageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg pakketype.
        /// </summary>
        public static string CreatePackageSelectTypeLabel {
            get {
                return ResourceManager.GetString("CreatePackageSelectTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIP.
        /// </summary>
        public static string CreatePackageTypeAIP {
            get {
                return ResourceManager.GetString("CreatePackageTypeAIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIP.
        /// </summary>
        public static string CreatePackageTypeSIP {
            get {
                return ResourceManager.GetString("CreatePackageTypeSIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opprett pakke.
        /// </summary>
        public static string CreatePackageWindowTitle {
            get {
                return ResourceManager.GetString("CreatePackageWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det oppstod en feil med den valgte filen.
        /// </summary>
        public static string FileException_ErrorWithChosenFile {
            get {
                return ResourceManager.GetString("FileException_ErrorWithChosenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det oppstod en generell feil med filvalget.
        /// </summary>
        public static string FileException_GeneralError {
            get {
                return ResourceManager.GetString("FileException_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen fil ble valgt.
        /// </summary>
        public static string FileException_NoFileChosen {
            get {
                return ResourceManager.GetString("FileException_NoFileChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .tar.
        /// </summary>
        public static string FileSelectionDefaultTar {
            get {
                return ResourceManager.GetString("FileSelectionDefaultTar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAR Files (*.tar)|*.tar|All Files (*.*)|*.*.
        /// </summary>
        public static string FileSelectionFilterTar {
            get {
                return ResourceManager.GetString("FileSelectionFilterTar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg en arkiv fil.
        /// </summary>
        public static string FileSelectionWindowNameArchive {
            get {
                return ResourceManager.GetString("FileSelectionWindowNameArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkade 5 - versjon {0}.
        /// </summary>
        public static string General_WindowTitle {
            get {
                return ResourceManager.GetString("General_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkivuttrekk.
        /// </summary>
        public static string LoadArchiveChooseArchiveHeadingText {
            get {
                return ResourceManager.GetString("LoadArchiveChooseArchiveHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg arkivtype.
        /// </summary>
        public static string LoadArchiveChooseArchiveTypeHeadingText {
            get {
                return ResourceManager.GetString("LoadArchiveChooseArchiveTypeHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg katalog.
        /// </summary>
        public static string LoadArchiveChooseFolderButtonText {
            get {
                return ResourceManager.GetString("LoadArchiveChooseFolderButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg SIP/AIP fil.
        /// </summary>
        public static string LoadArchiveChooseTarFileButtonText {
            get {
                return ResourceManager.GetString("LoadArchiveChooseTarFileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valgt fil.
        /// </summary>
        public static string LoadArchiveSelectedFileText {
            get {
                return ResourceManager.GetString("LoadArchiveSelectedFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valgt katalog.
        /// </summary>
        public static string LoadArchiveSelectedFolderText {
            get {
                return ResourceManager.GetString("LoadArchiveSelectedFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start testing.
        /// </summary>
        public static string LoadArchiveStartTestingButtonText {
            get {
                return ResourceManager.GetString("LoadArchiveStartTestingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fagsystem.
        /// </summary>
        public static string LoadArchiveTypeFagsystem {
            get {
                return ResourceManager.GetString("LoadArchiveTypeFagsystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noark3.
        /// </summary>
        public static string LoadArchiveTypeNoark3 {
            get {
                return ResourceManager.GetString("LoadArchiveTypeNoark3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noark4.
        /// </summary>
        public static string LoadArchiveTypeNoark4 {
            get {
                return ResourceManager.GetString("LoadArchiveTypeNoark4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noark5.
        /// </summary>
        public static string LoadArchiveTypeNoark5 {
            get {
                return ResourceManager.GetString("LoadArchiveTypeNoark5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last inn arkivuttrekk.
        /// </summary>
        public static string LoadArchiveViewHeadingText {
            get {
                return ResourceManager.GetString("LoadArchiveViewHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny kjøring.
        /// </summary>
        public static string NewProgramSessionButton {
            get {
                return ResourceManager.GetString("NewProgramSessionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Timestamp:yyyy-MM-ddTHH:mm:ss.fff} [{Level}] {SourceContext} {Message}{NewLine}{Exception}.
        /// </summary>
        public static string SerilogFormatConfig {
            get {
                return ResourceManager.GetString("SerilogFormatConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider gyldig xml.
        /// </summary>
        public static string TestName_CheckWellFormedXml {
            get {
                return ResourceManager.GetString("TestName_CheckWellFormedXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn antall arkivdeler.
        /// </summary>
        public static string TestName_NumberOfArchiveParts {
            get {
                return ResourceManager.GetString("TestName_NumberOfArchiveParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn antall arkiv.
        /// </summary>
        public static string TestName_NumberOfArchives {
            get {
                return ResourceManager.GetString("TestName_NumberOfArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn antall klasser.
        /// </summary>
        public static string TestName_NumberOfClasses {
            get {
                return ResourceManager.GetString("TestName_NumberOfClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn antall klasser i pri klassifikasjonssytem uten under klasser/mapper.
        /// </summary>
        public static string TestName_NumberOfClassesInMainClassificationSystemWithoutSubClassesorFolders {
            get {
                return ResourceManager.GetString("TestName_NumberOfClassesInMainClassificationSystemWithoutSubClassesorFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn antall klassifikasjonssystem.
        /// </summary>
        public static string TestName_NumberOfClassificationSystems {
            get {
                return ResourceManager.GetString("TestName_NumberOfClassificationSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn antall mapper.
        /// </summary>
        public static string TestName_NumberOfFolders {
            get {
                return ResourceManager.GetString("TestName_NumberOfFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn status på arkivdeler.
        /// </summary>
        public static string TestName_StatusOfArchiveParts {
            get {
                return ResourceManager.GetString("TestName_StatusOfArchiveParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider gyldig sjekksummer.
        /// </summary>
        public static string TestName_ValidateAddmlDataobjectsChecksums {
            get {
                return ResourceManager.GetString("TestName_ValidateAddmlDataobjectsChecksums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider xml i henhold til skjema.
        /// </summary>
        public static string TestName_ValidateXmlWithSchema {
            get {
                return ResourceManager.GetString("TestName_ValidateXmlWithSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testingen er fullført.
        /// </summary>
        public static string TestrunnerFinishedOperationMessage {
            get {
                return ResourceManager.GetString("TestrunnerFinishedOperationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feil under testkjøring.
        /// </summary>
        public static string TestrunnerFinishedWithError {
            get {
                return ResourceManager.GetString("TestrunnerFinishedWithError", resourceCulture);
            }
        }
    }
}
