//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arkivverket.Arkade.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Noark5Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Noark5Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arkivverket.Arkade.Resources.Noark5Messages", typeof(Noark5Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider xml (ADDML).
        /// </summary>
        internal static string CheckWellFormedArchiveStructureXml {
            get {
                return ResourceManager.GetString("CheckWellFormedArchiveStructureXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider xml (arkivvutrekk.xml).
        /// </summary>
        internal static string CheckWellFormedContentDescriptionXml {
            get {
                return ResourceManager.GetString("CheckWellFormedContentDescriptionXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrollér at refererte dokumenter eksisterer.
        /// </summary>
        internal static string ControlDocumentFilesExists {
            get {
                return ResourceManager.GetString("ControlDocumentFilesExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finner ikke filen..
        /// </summary>
        internal static string ControlDocumentsFilesExistsMessage1 {
            get {
                return ResourceManager.GetString("ControlDocumentsFilesExistsMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sjekksummen stemmer ikke for filen: {0}
        ///Forventet: {1}
        ///Generert:  {2}.
        /// </summary>
        internal static string ExceptionInvalidChecksum {
            get {
                return ResourceManager.GetString("ExceptionInvalidChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} er ikke gyldig i henhold til XML-skjema.
        ///{1}.
        /// </summary>
        internal static string ExceptionXmlDoesNotValidateWithSchema {
            get {
                return ResourceManager.GetString("ExceptionXmlDoesNotValidateWithSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn antall arkivdeler.
        /// </summary>
        internal static string NumberOfArchiveParts {
            get {
                return ResourceManager.GetString("NumberOfArchiveParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall arkivdeler: {0}.
        /// </summary>
        internal static string NumberOfArchivePartsMessage {
            get {
                return ResourceManager.GetString("NumberOfArchivePartsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn antall arkiv.
        /// </summary>
        internal static string NumberOfArchives {
            get {
                return ResourceManager.GetString("NumberOfArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall arkiv: {0}.
        /// </summary>
        internal static string NumberOfArchivesMessage {
            get {
                return ResourceManager.GetString("NumberOfArchivesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn antall saksparter.
        /// </summary>
        internal static string NumberOfCaseParts {
            get {
                return ResourceManager.GetString("NumberOfCaseParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall saksparter:{0}.
        /// </summary>
        internal static string NumberOfCasePartsMessage {
            get {
                return ResourceManager.GetString("NumberOfCasePartsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn antall klasser.
        /// </summary>
        internal static string NumberOfClasses {
            get {
                return ResourceManager.GetString("NumberOfClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall klasser i det primære klassifikasjonssystemet uten underklasser eller mapper.
        /// </summary>
        internal static string NumberOfClassesInMainClassificationSystemWithoutSubClassesorFolders {
            get {
                return ResourceManager.GetString("NumberOfClassesInMainClassificationSystemWithoutSubClassesorFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall klasser: {0}.
        /// </summary>
        internal static string NumberOfClassesMessage {
            get {
                return ResourceManager.GetString("NumberOfClassesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn antall klassifikasjonssystem.
        /// </summary>
        internal static string NumberOfClassificationSystems {
            get {
                return ResourceManager.GetString("NumberOfClassificationSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall klassifikasjonssystem: {0}.
        /// </summary>
        internal static string NumberOfClassificationSystemsMessage {
            get {
                return ResourceManager.GetString("NumberOfClassificationSystemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn antall merknader.
        /// </summary>
        internal static string NumberOfComments {
            get {
                return ResourceManager.GetString("NumberOfComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall merknader: {0}.
        /// </summary>
        internal static string NumberOfCommentsMessage {
            get {
                return ResourceManager.GetString("NumberOfCommentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn antall korrespondanseparter.
        /// </summary>
        internal static string NumberOfCorrespondenceParts {
            get {
                return ResourceManager.GetString("NumberOfCorrespondenceParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall korrespondanseparter: {0}.
        /// </summary>
        internal static string NumberOfCorrespondencePartsMessage {
            get {
                return ResourceManager.GetString("NumberOfCorrespondencePartsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall kryssreferanser.
        /// </summary>
        internal static string NumberOfCrossReferences {
            get {
                return ResourceManager.GetString("NumberOfCrossReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn antall avskrivninger.
        /// </summary>
        internal static string NumberOfDepreciations {
            get {
                return ResourceManager.GetString("NumberOfDepreciations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall avskrivninger: {0}.
        /// </summary>
        internal static string NumberOfDepreciationsMessage {
            get {
                return ResourceManager.GetString("NumberOfDepreciationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn antall dokumentbeskrivelser.
        /// </summary>
        internal static string NumberOfDocumentDescriptions {
            get {
                return ResourceManager.GetString("NumberOfDocumentDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall dokumentbeskrivelser: {0}.
        /// </summary>
        internal static string NumberOfDocumentDescriptionsMessage {
            get {
                return ResourceManager.GetString("NumberOfDocumentDescriptionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall dokumentbeskrivelser uten dokumentobjekt.
        /// </summary>
        internal static string NumberOfDocumentDescriptionsWithoutDocumentObject {
            get {
                return ResourceManager.GetString("NumberOfDocumentDescriptionsWithoutDocumentObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn antall dokumentflyter.
        /// </summary>
        internal static string NumberOfDocumentFlows {
            get {
                return ResourceManager.GetString("NumberOfDocumentFlows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall dokumentflyter: {0}.
        /// </summary>
        internal static string NumberOfDocumentFlowsMessage {
            get {
                return ResourceManager.GetString("NumberOfDocumentFlowsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn antall dokumentobjekter.
        /// </summary>
        internal static string NumberOfDocumentObjects {
            get {
                return ResourceManager.GetString("NumberOfDocumentObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall dokumentobjekter: {0}.
        /// </summary>
        internal static string NumberOfDocumentObjectsMessage {
            get {
                return ResourceManager.GetString("NumberOfDocumentObjectsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn antall mapper.
        /// </summary>
        internal static string NumberOfFolders {
            get {
                return ResourceManager.GetString("NumberOfFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall mapper: {0}.
        /// </summary>
        internal static string NumberOfFoldersMessage {
            get {
                return ResourceManager.GetString("NumberOfFoldersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall mapper for hvert år.
        /// </summary>
        internal static string NumberOfFoldersPerYear {
            get {
                return ResourceManager.GetString("NumberOfFoldersPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall mapper uten registreringer eller undermapper.
        /// </summary>
        internal static string NumberOfFoldersWithoutRegistrationsOrSubfolders {
            get {
                return ResourceManager.GetString("NumberOfFoldersWithoutRegistrationsOrSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn antall presedenser.
        /// </summary>
        internal static string NumberOfPrecedents {
            get {
                return ResourceManager.GetString("NumberOfPrecedents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall presedenser: {0}.
        /// </summary>
        internal static string NumberOfPrecedentsMessage {
            get {
                return ResourceManager.GetString("NumberOfPrecedentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn antall registreringer.
        /// </summary>
        internal static string NumberOfRegistrations {
            get {
                return ResourceManager.GetString("NumberOfRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall registreringer: {0}.
        /// </summary>
        internal static string NumberOfRegistrationsMessage {
            get {
                return ResourceManager.GetString("NumberOfRegistrationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall registreringer for hvert år.
        /// </summary>
        internal static string NumberOfRegistrationsPerYear {
            get {
                return ResourceManager.GetString("NumberOfRegistrationsPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall registreringer uten dokumentbeskrivelse.
        /// </summary>
        internal static string NumberOfRegistrationsWithoutDocumentDescription {
            get {
                return ResourceManager.GetString("NumberOfRegistrationsWithoutDocumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn status på arkivdeler.
        /// </summary>
        internal static string StatusOfArchiveParts {
            get {
                return ResourceManager.GetString("StatusOfArchiveParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider sjekksummer.
        /// </summary>
        internal static string ValidateAddmlDataobjectsChecksums {
            get {
                return ResourceManager.GetString("ValidateAddmlDataobjectsChecksums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider antallet dokumentfiler.
        /// </summary>
        internal static string ValidateNumberOfDocumentfiles {
            get {
                return ResourceManager.GetString("ValidateNumberOfDocumentfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall dokumentfiler ble ikke funnet oppgitt.
        /// </summary>
        internal static string ValidateNumberOfDocumentfilesMessage_DocumentationNotFound {
            get {
                return ResourceManager.GetString("ValidateNumberOfDocumentfilesMessage_DocumentationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det er ikke samsvar mellom oppgitt antall og faktisk antall dokumentfiler.
        /// </summary>
        internal static string ValidateNumberOfDocumentfilesMessage_FileAndDocumentationMismatch {
            get {
                return ResourceManager.GetString("ValidateNumberOfDocumentfilesMessage_FileAndDocumentationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen dokumentfilkatalog funnet.
        /// </summary>
        internal static string ValidateNumberOfDocumentfilesMessage_FilesDirectoryNotFound {
            get {
                return ResourceManager.GetString("ValidateNumberOfDocumentfilesMessage_FilesDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen dokumentfiler funnet.
        /// </summary>
        internal static string ValidateNumberOfDocumentfilesMessage_NoFilesFound {
            get {
                return ResourceManager.GetString("ValidateNumberOfDocumentfilesMessage_NoFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppgitt antall dokumentfiler: {0}.
        /// </summary>
        internal static string ValidateNumberOfDocumentfilesMessage_NumberOfFilesDocumented {
            get {
                return ResourceManager.GetString("ValidateNumberOfDocumentfilesMessage_NumberOfFilesDocumented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall dokumentfiler funnet: {0}.
        /// </summary>
        internal static string ValidateNumberOfDocumentfilesMessage_NumberOfFilesFound {
            get {
                return ResourceManager.GetString("ValidateNumberOfDocumentfilesMessage_NumberOfFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider xml i henhold til skjema (ADDML).
        /// </summary>
        internal static string ValidateXmlWithSchema {
            get {
                return ResourceManager.GetString("ValidateXmlWithSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validert i henhold til XML-skjema..
        /// </summary>
        internal static string ValidateXmlWithSchemaMessageValid {
            get {
                return ResourceManager.GetString("ValidateXmlWithSchemaMessageValid", resourceCulture);
            }
        }
    }
}
