//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arkivverket.Arkade.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Noark5TestNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Noark5TestNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arkivverket.Arkade.Resources.Noark5TestNames", typeof(Noark5TestNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkivdelreferanser.
        /// </summary>
        internal static string ArchivepartReferenceControl {
            get {
                return ResourceManager.GetString("ArchivepartReferenceControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start- og sluttdatoer.
        /// </summary>
        internal static string ArchiveStartAndEndDateControl {
            get {
                return ResourceManager.GetString("ArchiveStartAndEndDateControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endringslogg-referanser til arkivstrukturen.
        /// </summary>
        internal static string ChangeLogArchiveReferenceControl {
            get {
                return ResourceManager.GetString("ChangeLogArchiveReferenceControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klassereferanser.
        /// </summary>
        internal static string ClassReferenceControl {
            get {
                return ResourceManager.GetString("ClassReferenceControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refererte dokumenters eksistens.
        /// </summary>
        internal static string ControlDocumentFilesExists {
            get {
                return ResourceManager.GetString("ControlDocumentFilesExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasser med både underklasse(r) og mappe(r).
        /// </summary>
        internal static string ControlNoSuperclassesHasFolders {
            get {
                return ResourceManager.GetString("ControlNoSuperclassesHasFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasser med både underklasse(r) og registrering(er).
        /// </summary>
        internal static string ControlNoSuperclassesHasRegistrations {
            get {
                return ResourceManager.GetString("ControlNoSuperclassesHasRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentfilers sjekksummer.
        /// </summary>
        internal static string DocumentFilesChecksumControl {
            get {
                return ResourceManager.GetString("DocumentFilesChecksumControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentfiler som mangler referanse.
        /// </summary>
        internal static string DocumentfilesReferenceControl {
            get {
                return ResourceManager.GetString("DocumentfilesReferenceControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opprettelsesdatoer for første og siste registrering.
        /// </summary>
        internal static string FirstAndLastRegistrationCreationDates {
            get {
                return ResourceManager.GetString("FirstAndLastRegistrationCreationDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall arkivdeler.
        /// </summary>
        internal static string NumberOfArchiveParts {
            get {
                return ResourceManager.GetString("NumberOfArchiveParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall arkiv.
        /// </summary>
        internal static string NumberOfArchives {
            get {
                return ResourceManager.GetString("NumberOfArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall saksparter.
        /// </summary>
        internal static string NumberOfCaseParts {
            get {
                return ResourceManager.GetString("NumberOfCaseParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall loggførte endringer.
        /// </summary>
        internal static string NumberOfChangesLogged {
            get {
                return ResourceManager.GetString("NumberOfChangesLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall klasser.
        /// </summary>
        internal static string NumberOfClasses {
            get {
                return ResourceManager.GetString("NumberOfClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall klasser i det primære klassifikasjonssystemet uten underklasser, mapper eller registreringer.
        /// </summary>
        internal static string NumberOfClassesInMainClassificationSystemWithoutSubClassesorFolders {
            get {
                return ResourceManager.GetString("NumberOfClassesInMainClassificationSystemWithoutSubClassesorFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall graderinger.
        /// </summary>
        internal static string NumberOfClassifications {
            get {
                return ResourceManager.GetString("NumberOfClassifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall klassifikasjonssystem.
        /// </summary>
        internal static string NumberOfClassificationSystems {
            get {
                return ResourceManager.GetString("NumberOfClassificationSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall merknader.
        /// </summary>
        internal static string NumberOfComments {
            get {
                return ResourceManager.GetString("NumberOfComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall konverterte dokumenter.
        /// </summary>
        internal static string NumberOfConversions {
            get {
                return ResourceManager.GetString("NumberOfConversions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall korrespondanseparter.
        /// </summary>
        internal static string NumberOfCorrespondenceParts {
            get {
                return ResourceManager.GetString("NumberOfCorrespondenceParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall kryssreferanser.
        /// </summary>
        internal static string NumberOfCrossReferences {
            get {
                return ResourceManager.GetString("NumberOfCrossReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall avskrivninger.
        /// </summary>
        internal static string NumberOfDepreciations {
            get {
                return ResourceManager.GetString("NumberOfDepreciations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall kassasjonsvedtak.
        /// </summary>
        internal static string NumberOfDisposalResolutions {
            get {
                return ResourceManager.GetString("NumberOfDisposalResolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall utførte kassasjoner.
        /// </summary>
        internal static string NumberOfDisposalsExecuted {
            get {
                return ResourceManager.GetString("NumberOfDisposalsExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall dokumentbeskrivelser.
        /// </summary>
        internal static string NumberOfDocumentDescriptions {
            get {
                return ResourceManager.GetString("NumberOfDocumentDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall dokumentbeskrivelser uten dokumentobjekt.
        /// </summary>
        internal static string NumberOfDocumentDescriptionsWithoutDocumentObject {
            get {
                return ResourceManager.GetString("NumberOfDocumentDescriptionsWithoutDocumentObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall dokumentflyter.
        /// </summary>
        internal static string NumberOfDocumentFlows {
            get {
                return ResourceManager.GetString("NumberOfDocumentFlows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall dokumentobjekter.
        /// </summary>
        internal static string NumberOfDocumentObjects {
            get {
                return ResourceManager.GetString("NumberOfDocumentObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall av ulike saksmappestatuser.
        /// </summary>
        internal static string NumberOfEachCaseFolderStatus {
            get {
                return ResourceManager.GetString("NumberOfEachCaseFolderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall av ulike dokumentformater.
        /// </summary>
        internal static string NumberOfEachDocumentFormat {
            get {
                return ResourceManager.GetString("NumberOfEachDocumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall av ulike dokumentstatuser.
        /// </summary>
        internal static string NumberOfEachDocumentStatus {
            get {
                return ResourceManager.GetString("NumberOfEachDocumentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall av ulike journalposttyper.
        /// </summary>
        internal static string NumberOfEachJournalPostType {
            get {
                return ResourceManager.GetString("NumberOfEachJournalPostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall av ulike journalstatuser.
        /// </summary>
        internal static string NumberOfEachJournalStatus {
            get {
                return ResourceManager.GetString("NumberOfEachJournalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall mapper.
        /// </summary>
        internal static string NumberOfFolders {
            get {
                return ResourceManager.GetString("NumberOfFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall mapper for hver klasse.
        /// </summary>
        internal static string NumberOfFoldersPerClass {
            get {
                return ResourceManager.GetString("NumberOfFoldersPerClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall mapper for hvert år.
        /// </summary>
        internal static string NumberOfFoldersPerYear {
            get {
                return ResourceManager.GetString("NumberOfFoldersPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall mapper uten registreringer eller undermapper.
        /// </summary>
        internal static string NumberOfFoldersWithoutRegistrationsOrSubfolders {
            get {
                return ResourceManager.GetString("NumberOfFoldersWithoutRegistrationsOrSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall journalposter.
        /// </summary>
        internal static string NumberOfJournalPosts {
            get {
                return ResourceManager.GetString("NumberOfJournalPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentfiler med referanse fra mer enn ett dokumentobjekt.
        /// </summary>
        internal static string NumberOfMultiReferencedDocumentFiles {
            get {
                return ResourceManager.GetString("NumberOfMultiReferencedDocumentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall presedenser.
        /// </summary>
        internal static string NumberOfPrecedents {
            get {
                return ResourceManager.GetString("NumberOfPrecedents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall registreringer.
        /// </summary>
        internal static string NumberOfRegistrations {
            get {
                return ResourceManager.GetString("NumberOfRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall registreringer for hver klasse (ikke medregnet registreringer under mappe).
        /// </summary>
        internal static string NumberOfRegistrationsPerClass {
            get {
                return ResourceManager.GetString("NumberOfRegistrationsPerClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall registreringer for hvert år.
        /// </summary>
        internal static string NumberOfRegistrationsPerYear {
            get {
                return ResourceManager.GetString("NumberOfRegistrationsPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall registreringer uten dokumentbeskrivelse.
        /// </summary>
        internal static string NumberOfRegistrationsWithoutDocumentDescription {
            get {
                return ResourceManager.GetString("NumberOfRegistrationsWithoutDocumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall skjerminger.
        /// </summary>
        internal static string NumberOfRestrictions {
            get {
                return ResourceManager.GetString("NumberOfRestrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status på arkivdeler.
        /// </summary>
        internal static string StatusOfArchiveParts {
            get {
                return ResourceManager.GetString("StatusOfArchiveParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systemidentifikasjoner.
        /// </summary>
        internal static string SystemIdUniqueControl {
            get {
                return ResourceManager.GetString("SystemIdUniqueControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validering av sjekksummer.
        /// </summary>
        internal static string ValidateAddmlDataobjectsChecksums {
            get {
                return ResourceManager.GetString("ValidateAddmlDataobjectsChecksums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validering av antall dokumentfiler.
        /// </summary>
        internal static string ValidateNumberOfDocumentfiles {
            get {
                return ResourceManager.GetString("ValidateNumberOfDocumentfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validering av XML i henhold til skjema.
        /// </summary>
        internal static string ValidateXmlWithSchema {
            get {
                return ResourceManager.GetString("ValidateXmlWithSchema", resourceCulture);
            }
        }
    }
}
