//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:4.0.30319.42000
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Arkivverket.Arkade.Core.ExternalModels.Siard1Metadata {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd", IsNullable=false)]
    public partial class siardArchive {
        
        private string dbnameField;
        
        private string descriptionField;
        
        private string archiverField;
        
        private string archiverContactField;
        
        private string dataOwnerField;
        
        private string dataOriginTimespanField;
        
        private string producerApplicationField;
        
        private System.DateTime archivalDateField;
        
        private string messageDigestField;
        
        private string clientMachineField;
        
        private string databaseProductField;
        
        private string connectionField;
        
        private string databaseUserField;
        
        private schemaType[] schemasField;
        
        private userType[] usersField;
        
        private roleType[] rolesField;
        
        private privilegeType[] privilegesField;
        
        private versionType versionField;
        
        /// <remarks/>
        public string dbname {
            get {
                return this.dbnameField;
            }
            set {
                this.dbnameField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string archiver {
            get {
                return this.archiverField;
            }
            set {
                this.archiverField = value;
            }
        }
        
        /// <remarks/>
        public string archiverContact {
            get {
                return this.archiverContactField;
            }
            set {
                this.archiverContactField = value;
            }
        }
        
        /// <remarks/>
        public string dataOwner {
            get {
                return this.dataOwnerField;
            }
            set {
                this.dataOwnerField = value;
            }
        }
        
        /// <remarks/>
        public string dataOriginTimespan {
            get {
                return this.dataOriginTimespanField;
            }
            set {
                this.dataOriginTimespanField = value;
            }
        }
        
        /// <remarks/>
        public string producerApplication {
            get {
                return this.producerApplicationField;
            }
            set {
                this.producerApplicationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime archivalDate {
            get {
                return this.archivalDateField;
            }
            set {
                this.archivalDateField = value;
            }
        }
        
        /// <remarks/>
        public string messageDigest {
            get {
                return this.messageDigestField;
            }
            set {
                this.messageDigestField = value;
            }
        }
        
        /// <remarks/>
        public string clientMachine {
            get {
                return this.clientMachineField;
            }
            set {
                this.clientMachineField = value;
            }
        }
        
        /// <remarks/>
        public string databaseProduct {
            get {
                return this.databaseProductField;
            }
            set {
                this.databaseProductField = value;
            }
        }
        
        /// <remarks/>
        public string connection {
            get {
                return this.connectionField;
            }
            set {
                this.connectionField = value;
            }
        }
        
        /// <remarks/>
        public string databaseUser {
            get {
                return this.databaseUserField;
            }
            set {
                this.databaseUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("schema", IsNullable=false)]
        public schemaType[] schemas {
            get {
                return this.schemasField;
            }
            set {
                this.schemasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("user", IsNullable=false)]
        public userType[] users {
            get {
                return this.usersField;
            }
            set {
                this.usersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("role", IsNullable=false)]
        public roleType[] roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("privilege", IsNullable=false)]
        public privilegeType[] privileges {
            get {
                return this.privilegesField;
            }
            set {
                this.privilegesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public versionType version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd")]
    public partial class schemaType {
        
        private string nameField;
        
        private string folderField;
        
        private string descriptionField;
        
        private tableType[] tablesField;
        
        private viewType[] viewsField;
        
        private routineType[] routinesField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("table", IsNullable=false)]
        public tableType[] tables {
            get {
                return this.tablesField;
            }
            set {
                this.tablesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("view", IsNullable=false)]
        public viewType[] views {
            get {
                return this.viewsField;
            }
            set {
                this.viewsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("routine", IsNullable=false)]
        public routineType[] routines {
            get {
                return this.routinesField;
            }
            set {
                this.routinesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd")]
    public partial class tableType {
        
        private string nameField;
        
        private string folderField;
        
        private string descriptionField;
        
        private columnType[] columnsField;
        
        private primaryKeyType primaryKeyField;
        
        private foreignKeyType[] foreignKeysField;
        
        private candidateKeyType[] candidateKeysField;
        
        private checkConstraintType[] checkConstraintsField;
        
        private triggerType[] triggersField;
        
        private string rowsField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("column", IsNullable=false)]
        public columnType[] columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
            }
        }
        
        /// <remarks/>
        public primaryKeyType primaryKey {
            get {
                return this.primaryKeyField;
            }
            set {
                this.primaryKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("foreignKey", IsNullable=false)]
        public foreignKeyType[] foreignKeys {
            get {
                return this.foreignKeysField;
            }
            set {
                this.foreignKeysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("candidateKey", IsNullable=false)]
        public candidateKeyType[] candidateKeys {
            get {
                return this.candidateKeysField;
            }
            set {
                this.candidateKeysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("checkConstraint", IsNullable=false)]
        public checkConstraintType[] checkConstraints {
            get {
                return this.checkConstraintsField;
            }
            set {
                this.checkConstraintsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("trigger", IsNullable=false)]
        public triggerType[] triggers {
            get {
                return this.triggersField;
            }
            set {
                this.triggersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd")]
    public partial class columnType {
        
        private string nameField;
        
        private string folderField;
        
        private string typeField;
        
        private string typeOriginalField;
        
        private string defaultValueField;
        
        private bool nullableField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string typeOriginal {
            get {
                return this.typeOriginalField;
            }
            set {
                this.typeOriginalField = value;
            }
        }
        
        /// <remarks/>
        public string defaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
            }
        }
        
        /// <remarks/>
        public bool nullable {
            get {
                return this.nullableField;
            }
            set {
                this.nullableField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd")]
    public partial class privilegeType {
        
        private string typeField;
        
        private string objectField;
        
        private string grantorField;
        
        private string granteeField;
        
        private privOptionType optionField;
        
        private bool optionFieldSpecified;
        
        private string descriptionField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string @object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
            }
        }
        
        /// <remarks/>
        public string grantor {
            get {
                return this.grantorField;
            }
            set {
                this.grantorField = value;
            }
        }
        
        /// <remarks/>
        public string grantee {
            get {
                return this.granteeField;
            }
            set {
                this.granteeField = value;
            }
        }
        
        /// <remarks/>
        public privOptionType option {
            get {
                return this.optionField;
            }
            set {
                this.optionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool optionSpecified {
            get {
                return this.optionFieldSpecified;
            }
            set {
                this.optionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd")]
    public enum privOptionType {
        
        /// <remarks/>
        ADMIN,
        
        /// <remarks/>
        GRANT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd")]
    public partial class roleType {
        
        private string nameField;
        
        private string adminField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string admin {
            get {
                return this.adminField;
            }
            set {
                this.adminField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd")]
    public partial class userType {
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd")]
    public partial class parameterType {
        
        private string nameField;
        
        private string modeField;
        
        private string typeField;
        
        private string typeOriginalField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string typeOriginal {
            get {
                return this.typeOriginalField;
            }
            set {
                this.typeOriginalField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd")]
    public partial class routineType {
        
        private string nameField;
        
        private string descriptionField;
        
        private string sourceField;
        
        private string bodyField;
        
        private string characteristicField;
        
        private string returnTypeField;
        
        private parameterType[] parametersField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        public string characteristic {
            get {
                return this.characteristicField;
            }
            set {
                this.characteristicField = value;
            }
        }
        
        /// <remarks/>
        public string returnType {
            get {
                return this.returnTypeField;
            }
            set {
                this.returnTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter", IsNullable=false)]
        public parameterType[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd")]
    public partial class viewType {
        
        private string nameField;
        
        private string queryField;
        
        private string queryOriginalField;
        
        private string descriptionField;
        
        private columnType[] columnsField;
        
        private string rowsField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
        
        /// <remarks/>
        public string queryOriginal {
            get {
                return this.queryOriginalField;
            }
            set {
                this.queryOriginalField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("column", IsNullable=false)]
        public columnType[] columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd")]
    public partial class triggerType {
        
        private string nameField;
        
        private actionTimeType actionTimeField;
        
        private string triggerEventField;
        
        private string aliasListField;
        
        private string triggeredActionField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public actionTimeType actionTime {
            get {
                return this.actionTimeField;
            }
            set {
                this.actionTimeField = value;
            }
        }
        
        /// <remarks/>
        public string triggerEvent {
            get {
                return this.triggerEventField;
            }
            set {
                this.triggerEventField = value;
            }
        }
        
        /// <remarks/>
        public string aliasList {
            get {
                return this.aliasListField;
            }
            set {
                this.aliasListField = value;
            }
        }
        
        /// <remarks/>
        public string triggeredAction {
            get {
                return this.triggeredActionField;
            }
            set {
                this.triggeredActionField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd")]
    public enum actionTimeType {
        
        /// <remarks/>
        BEFORE,
        
        /// <remarks/>
        AFTER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd")]
    public partial class checkConstraintType {
        
        private string nameField;
        
        private string conditionField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd")]
    public partial class candidateKeyType {
        
        private string nameField;
        
        private string descriptionField;
        
        private string[] columnField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("column")]
        public string[] column {
            get {
                return this.columnField;
            }
            set {
                this.columnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd")]
    public partial class referenceType {
        
        private string columnField;
        
        private string referencedField;
        
        /// <remarks/>
        public string column {
            get {
                return this.columnField;
            }
            set {
                this.columnField = value;
            }
        }
        
        /// <remarks/>
        public string referenced {
            get {
                return this.referencedField;
            }
            set {
                this.referencedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd")]
    public partial class foreignKeyType {
        
        private string nameField;
        
        private string referencedSchemaField;
        
        private string referencedTableField;
        
        private referenceType[] referenceField;
        
        private matchTypeType matchTypeField;
        
        private bool matchTypeFieldSpecified;
        
        private string deleteActionField;
        
        private string updateActionField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string referencedSchema {
            get {
                return this.referencedSchemaField;
            }
            set {
                this.referencedSchemaField = value;
            }
        }
        
        /// <remarks/>
        public string referencedTable {
            get {
                return this.referencedTableField;
            }
            set {
                this.referencedTableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reference")]
        public referenceType[] reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public matchTypeType matchType {
            get {
                return this.matchTypeField;
            }
            set {
                this.matchTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool matchTypeSpecified {
            get {
                return this.matchTypeFieldSpecified;
            }
            set {
                this.matchTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string deleteAction {
            get {
                return this.deleteActionField;
            }
            set {
                this.deleteActionField = value;
            }
        }
        
        /// <remarks/>
        public string updateAction {
            get {
                return this.updateActionField;
            }
            set {
                this.updateActionField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd")]
    public enum matchTypeType {
        
        /// <remarks/>
        FULL,
        
        /// <remarks/>
        PARTIAL,
        
        /// <remarks/>
        SIMPLE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd")]
    public partial class primaryKeyType {
        
        private string nameField;
        
        private string descriptionField;
        
        private string[] columnField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("column")]
        public string[] column {
            get {
                return this.columnField;
            }
            set {
                this.columnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd")]
    public enum versionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.0")]
        Item10,
    }
}
