//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:4.0.30319.42000
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Arkivverket.Arkade.Core.ExternalModels.TestSessionLog {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/dataextracttools/arkade5/testsessionlog")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.arkivverket.no/dataextracttools/arkade5/testsessionlog", IsNullable=false)]
    public partial class testSessionLog {
        
        private object timestampField;
        
        private string archiveUuidField;
        
        private string archiveTypeField;
        
        private string arkadeVersionField;
        
        private testResultsTestResult[] testResultsField;
        
        private logEntriesLogEntry[] logEntriesField;
        
        /// <remarks/>
        public object timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public string archiveUuid {
            get {
                return this.archiveUuidField;
            }
            set {
                this.archiveUuidField = value;
            }
        }
        
        /// <remarks/>
        public string archiveType {
            get {
                return this.archiveTypeField;
            }
            set {
                this.archiveTypeField = value;
            }
        }
        
        /// <remarks/>
        public string arkadeVersion {
            get {
                return this.arkadeVersionField;
            }
            set {
                this.arkadeVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("testResult", IsNullable=false)]
        public testResultsTestResult[] testResults {
            get {
                return this.testResultsField;
            }
            set {
                this.testResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("logEntry", IsNullable=false)]
        public logEntriesLogEntry[] logEntries {
            get {
                return this.logEntriesField;
            }
            set {
                this.logEntriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.arkivverket.no/dataextracttools/arkade5/testsessionlog")]
    public partial class testResultsTestResult {
        
        private string testNameField;
        
        private string testCategoryField;
        
        private string testDescriptionField;
        
        private string durationMillisField;
        
        private string statusField;
        
        private string messageField;
        
        /// <remarks/>
        public string testName {
            get {
                return this.testNameField;
            }
            set {
                this.testNameField = value;
            }
        }
        
        /// <remarks/>
        public string testCategory {
            get {
                return this.testCategoryField;
            }
            set {
                this.testCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string testDescription {
            get {
                return this.testDescriptionField;
            }
            set {
                this.testDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string durationMillis {
            get {
                return this.durationMillisField;
            }
            set {
                this.durationMillisField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.arkivverket.no/dataextracttools/arkade5/testsessionlog")]
    public partial class logEntriesLogEntry {
        
        private System.DateTime timestampField;
        
        private string messageField;
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
}
